name: Build luci-app-ssr-plus

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OpenWrt SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build luci-app-ssr-plus
        run: |
          cd openwrt
          make package/luci-app-ssr-plus/compile V=s

      - name: Upload artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: luci-app-ssr-plus
          path: openwrt/bin/packages/
