name: Build luci-app-ssr-plus

on:
  push:
    branches:
      - main  # 或者你选择的其他分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git
          sudo apt-get install -y python python3 python3-pip

      - name: Build luci-app-ssr-plus
        run: |
          cd ./packages/luci-app-ssr-plus  # 更改为luci-app-ssr-plus的路径
          make package/luci-app-ssr-plus/compile V=s
